/**
 * Painting catalog for Rafael Gonzaga Virtual Art Gallery
 * 33 paintings organized into 5 thematic groups
 */

export const groups = [
  {
    id: 'portraits',
    title: 'Portraits & Figures',
    description: 'His face, his family, the human form — where every painting begins.',
  },
  {
    id: 'philippines',
    title: 'The Philippines',
    description: 'Landscapes, villages, and memories of home.',
  },
  {
    id: 'philadelphia',
    title: 'Philadelphia & Urban Scenes',
    description: 'Row houses, rooftops, and the streets of his adopted city.',
  },
  {
    id: 'still-life',
    title: 'Still Life & Academic Work',
    description: 'The discipline of observation — geometric forms, flowers, everyday objects.',
  },
  {
    id: 'abstract',
    title: 'Abstract & Symbolic Works',
    description: 'Inner worlds, cultural memory, and the space between two countries.',
  },
]

export const paintings = [
  // === Group 1: Portraits & Figures ===
  {
    file: 'IMG_1253',
    ext: 'jpeg',
    title: 'Self-Portrait',
    group: 'portraits',
    year: null,
    rotate: 90,
    hero: true,
  },
  {
    file: 'IMG_1269',
    ext: 'jpg',
    title: 'Portrait of a Child',
    group: 'portraits',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1261',
    ext: 'jpeg',
    title: 'Girl in a Forest',
    group: 'portraits',
    year: null,
    rotate: 90,
  },
  {
    file: 'IMG_1255',
    ext: 'jpeg',
    title: 'Figure Study — Torso',
    group: 'portraits',
    year: null,
    rotate: 90,
  },
  {
    file: 'IMG_1260',
    ext: 'jpeg',
    title: 'Reclining Figure',
    group: 'portraits',
    year: null,
    rotate: 90,
  },
  {
    file: 'IMG_1268',
    ext: 'jpg',
    title: 'Figure in Red and Orange',
    group: 'portraits',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1256',
    ext: 'jpeg',
    title: 'Abstract Figure Composition',
    group: 'portraits',
    year: null,
    rotate: 0,
  },

  // === Group 2: The Philippines ===
  {
    file: 'IMG_1270',
    ext: 'jpg',
    title: 'Mountain Lake',
    group: 'philippines',
    year: 1987,
    rotate: 0,
  },
  {
    file: 'IMG_1294',
    ext: 'jpg',
    title: 'Rural Scene with Yellow Umbrella',
    group: 'philippines',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1267',
    ext: 'jpeg',
    title: 'Village Fiesta',
    group: 'philippines',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1284',
    ext: 'jpg',
    title: 'Family Dinner',
    group: 'philippines',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1293',
    ext: 'jpg',
    title: 'Colorful Village',
    group: 'philippines',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1258',
    ext: 'jpeg',
    title: 'Abstract Village',
    group: 'philippines',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1290',
    ext: 'jpg',
    title: 'Cultural Composition',
    group: 'philippines',
    year: null,
    rotate: 0,
  },

  // === Group 3: Philadelphia & Urban Scenes ===
  {
    file: 'IMG_1272',
    ext: 'jpg',
    title: 'Voorhees Neighborhood',
    group: 'philadelphia',
    year: 1993,
    rotate: 0,
  },
  {
    file: 'IMG_1259',
    ext: 'jpg',
    title: 'Rooftop Cityscape',
    group: 'philadelphia',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1285',
    ext: 'jpg',
    title: 'Street Corner',
    group: 'philadelphia',
    year: 1990,
    rotate: 0,
  },
  {
    file: 'IMG_1271',
    ext: 'jpeg',
    title: 'Urban Abstract',
    group: 'philadelphia',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1273',
    ext: 'jpeg',
    title: 'Street Scene',
    group: 'philadelphia',
    year: null,
    rotate: 90,
  },
  {
    file: 'IMG_1274',
    ext: 'jpeg',
    title: 'Figures in Architecture',
    group: 'philadelphia',
    year: null,
    rotate: 0,
  },

  // === Group 4: Still Life & Academic Work ===
  {
    file: 'IMG_1296',
    ext: 'JPG',
    title: 'Geometric Still Life (Cool)',
    group: 'still-life',
    year: 1990,
    rotate: 0,
  },
  {
    file: 'IMG_1295',
    ext: 'jpg',
    title: 'Geometric Still Life (Warm)',
    group: 'still-life',
    year: 1990,
    rotate: 0,
  },
  {
    file: 'IMG_1254',
    ext: 'jpg',
    title: 'Complex Still Life',
    group: 'still-life',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1291',
    ext: 'jpg',
    title: 'Kitchen Still Life',
    group: 'still-life',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1292',
    ext: 'jpg',
    title: 'Desk Objects',
    group: 'still-life',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1283',
    ext: 'jpg',
    title: 'Magnolias',
    group: 'still-life',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1266',
    ext: 'jpeg',
    title: 'Red Flower',
    group: 'still-life',
    year: null,
    rotate: 90,
  },

  // === Group 5: Abstract & Symbolic Works ===
  {
    file: 'IMG_1286',
    ext: 'jpg',
    title: 'Archway with Moon and Flag',
    group: 'abstract',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1264',
    ext: 'jpeg',
    title: 'Abstract Composition',
    group: 'abstract',
    year: 1990,
    rotate: 90,
  },
  {
    file: 'IMG_1287',
    ext: 'jpeg',
    title: 'Dark Still Life',
    group: 'abstract',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1288',
    ext: 'jpeg',
    title: 'Red and Green Forms',
    group: 'abstract',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1289',
    ext: 'jpg',
    title: 'Dark Interior',
    group: 'abstract',
    year: null,
    rotate: 0,
  },
  {
    file: 'IMG_1257',
    ext: 'jpg',
    title: 'Church Scene',
    group: 'abstract',
    year: null,
    rotate: 0,
  },
]
